import React from "react";
import Sidebar from "../components/Sidebar";
import LeadsGenerated from "../assets/LeadsGenerated.png";
import LeadsReturned from "../assets/LeadsReturned.png";
import Revenue from "../assets/Revenue.png";
import VendorsAdded from "../assets/VendorsAdded.png";

import {
    AreaChart,
    Area,
    XAxis,
    YAxis,
    CartesianGrid,
    Tooltip,
    ResponsiveContainer,
} from "recharts";

const chartData = [
    { day: "1", leads: 520 },
    { day: "2", leads: 580 },
    { day: "3", leads: 650 },
    { day: "4", leads: 580 },
    { day: "5", leads: 700 },
    { day: "6", leads: 550 },
    { day: "7", leads: 680 },
    { day: "8", leads: 620 },
    { day: "9", leads: 700 },
    { day: "10", leads: 650 },
    { day: "11", leads: 580 },
    { day: "12", leads: 520 },
];

export default function Dashboard() {
    return (
        <>
            {/* Import Poppins Font */}
            <style>
                {`
                    @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800&display=swap');
                    
                    * {
                        font-family: 'Poppins', sans-serif;
                    }
                `}
            </style>

            <div className="flex">
                {/* Fixed Sidebar */}
                <Sidebar />

                {/* Main Scrollable Content */}
                <div className="flex-1 ml-64 p-6 bg-gray-50 min-h-screen overflow-y-auto">
                    {/* Top Stats */}
                    <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-6">
                        <StatCard
                            title="Leads Generated"
                            value="24"
                            percent="+0.06%"
                            percentColor="#414A73"
                            percentbgColor="#ABFF59"
                            image={LeadsGenerated}
                        />
                        <StatCard
                            title="Leads Returned"
                            value="10"
                            percent="-12.9%"
                            percentColor="#FFFFFF"
                            percentbgColor="#FE6331"
                            image={LeadsReturned}
                        />
                        <StatCard
                            title="Revenue"
                            value="$135000"
                            percent="+46.8%"
                            percentColor="#414A73"
                            percentbgColor="#FFF06B"
                            image={Revenue}
                        />
                        <StatCard
                            title="Vendors Added Total"
                            value="150"
                            percent="+34.9%"
                            percentColor="#414A73"
                            percentbgColor="#ABFF59"
                            image={VendorsAdded}
                        />
                    </div>

                    {/* Chart & Top Visiting Pages */}
                    <div className="grid grid-cols-1 lg:grid-cols-3 gap-4 mb-6">
                        {/* Chart Section */}
                        <div className="lg:col-span-2 bg-gradient-to-br from-gray-900 to-gray-800 text-white p-6 rounded-2xl shadow-lg">
                            <div className="flex justify-between items-center mb-4">
                                <h2 className="text-[18px] font-poppins text-white font-medium">Leads Generated by Day</h2>
                            </div>
                            <div style={{ height: 280 }}>
                                <ResponsiveContainer width="100%" height="100%">
                                    <AreaChart data={chartData}>
                                        <defs>
                                            <linearGradient id="leadColor" x1="0" y1="0" x2="0" y2="1">
                                                <stop offset="5%" stopColor="#fb923c" stopOpacity={0.6} />
                                                <stop offset="95%" stopColor="#fb923c" stopOpacity={0} />
                                            </linearGradient>
                                        </defs>
                                        <CartesianGrid
                                            strokeDasharray="3 3"
                                            stroke="#374151"
                                            opacity={0.3}
                                        />
                                        <XAxis
                                            dataKey="day"
                                            stroke="#9ca3af"
                                            tick={{ fill: "#9ca3af", fontSize: 12 }}
                                            style={{ fontFamily: 'Poppins, sans-serif' }}
                                        />
                                        <YAxis
                                            stroke="#9ca3af"
                                            tick={{ fill: "#9ca3af", fontSize: 12 }}
                                            style={{ fontFamily: 'Poppins, sans-serif' }}
                                        />
                                        <Tooltip
                                            contentStyle={{
                                                backgroundColor: "#1f2937",
                                                border: "none",
                                                borderRadius: "8px",
                                                color: "#fff",
                                                fontFamily: 'Poppins, sans-serif'
                                            }}
                                        />
                                        <Area
                                            type="monotone"
                                            dataKey="leads"
                                            stroke="#fb923c"
                                            fill="url(#leadColor)"
                                            strokeWidth={3}
                                        />
                                    </AreaChart>
                                </ResponsiveContainer>
                            </div>
                        </div>

                        {/* Top Visiting Pages */}
                        <div className="bg-gradient-to-br from-gray-900 to-gray-800 p-6 rounded-2xl shadow-lg">
                            <h2 className="text-[18px] font-poppins font-medium text-white mb-6">
                                Top Visiting Pages
                            </h2>
                            <div className="space-y-1">
                                <div className="grid grid-cols-[2fr,1fr,1fr] gap-4 text-[13px] font-poppins text-gray-400 font-medium pb-3 border-b border-gray-700">
                                    <span>Item Full Name</span>
                                    <span className="text-center">Quantity</span>
                                    <span className="text-right">Sales Order</span>
                                </div>
                                {[
                                    { name: "Birthday photography", qty: "618", sales: "$214K" },
                                    { name: "Naming Ceremony decoration", qty: "1721", sales: "$172K" },
                                    { name: "Wedding Makeup", qty: "1206", sales: "$121K" },
                                    { name: "Wedding catering", qty: "776", sales: "$85K" },
                                    { name: "Wedding Decoration", qty: "530", sales: "$81K" },
                                    { name: "Wedding Photography", qty: "593", sales: "$77K" },
                                    { name: "Babyshower decoration", qty: "321", sales: "$68K" },
                                    { name: "Birthday event management", qty: "680", sales: "$67K" },
                                ].map((item, idx) => (
                                    <div
                                        key={idx}
                                        className="grid grid-cols-[2fr,1fr,1fr]  items-center"
                                    >
                                        <span className="text-white text-[13px] font-normal font-poppins whitespace-nowrap overflow-hidden text-ellipsis">
                                            {item.name}
                                        </span>

                                        <span className="text-center text-white text-[13px] font-normal font-poppins ">
                                            {item.qty}
                                        </span>
                                        <div className="flex justify-end">
                                            <span className="bg-orange-500 text-white text-[13px] font-normal font-poppins px-4  rounded-md">
                                                {item.sales}
                                            </span>
                                        </div>
                                    </div>
                                ))}
                            </div>
                        </div>
                    </div>

                    {/* Vendors Brief Data & Quick Actions */}
                    <div className="grid grid-cols-1 lg:grid-cols-4 gap-4">
                        <div className="lg:col-span-3">
                            <h2 className="text-lg font-semibold mb-4 text-gray-900">
                                Vendors Brief Data
                            </h2>
                            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                                <StatCard
                                    title="Active Vendors"
                                    value="24"
                                    percent="+14.98%"
                                    percentColor="#414A73"
                                    percentbgColor="#ABFF59"
                                    image={LeadsGenerated}
                                />
                                <StatCard
                                    title="Total Vendors"
                                    value="100"
                                    percent="-12.78%"
                                    percentColor="#414A73"
                                    percentbgColor="#FE6331"
                                    image={LeadsReturned}
                                />
                                <StatCard
                                    title="Renewal Upcoming"
                                    value="135"
                                // icon="📅"
                                />
                            </div>

                            {/* Pages Data */}
                            <div className="mt-6">
                                <h2 className="text-lg font-semibold mb-4 text-gray-900">
                                    Pages Data
                                </h2>
                                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                                    <StatCard
                                        title="Active Pages"
                                        value="24"
                                        percent="+14.98%"
                                        percentColor="#414A73"
                                        percentbgColor="#ABFF59"
                                        image={LeadsGenerated}
                                    />
                                    <StatCard
                                        title="Draft Pages"
                                        value="10"
                                    // icon="📄"
                                    />
                                    <StatCard
                                        title="Total Articles"
                                        value="100"
                                        percent="-12.79%"
                                        percentColor="#414A73"
                                        percentbgColor="#FE6331"
                                        image={LeadsReturned}
                                    />
                                </div>
                            </div>
                        </div>

                        {/* Quick Actions */}
                        <div className="bg-white p-6  rounded-2xl shadow-sm border border-gray-100">
                            <h2 className="text-lg font-semibold mb-44 text-gray-900">
                                Quick Actions
                            </h2>
                            <div className="space-y-3">
                                <button className="w-full px-4 py-3 border border-black text-sm font-medium text-gray-900 hover:bg-gray-50 transition">
                                    Create Page
                                </button>
                                <button className="w-full px-4 py-3 border border-black text-sm font-medium text-gray-900 hover:bg-gray-50 transition">
                                    Write New Article
                                </button>
                                <button className="w-full px-4 py-3 border border-black text-sm font-medium text-gray-900 hover:bg-gray-50 transition">
                                    Add New Vendor
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </>
    );
}


function StatCard({ title, value, percent, percentColor, icon, image, percentbgColor }) {
    return (
        <div className="bg-white p-5 rounded-2xl shadow-sm border border-gray-100">
            <div className="flex items-start justify-between mb-3">
                <h3 className="text-[#414A73] text-[16px] font-semibold">{title}</h3>

                {/* If image provided, show it; else show emoji icon */}
                {image ? (
                    <img
                        src={image}
                        alt={title}
                        className="w-8 h-8 object-contain"
                    />
                ) : (
                    <span className="text-2xl">{icon}</span>
                )}
            </div>
            <p className="text-3xl font-bold text-[#414A73] mb-2">{value}</p>
            {percent && (
                <p className="text-xs font-medium flex items-center gap-2 flex-wrap">
                    <span
                        className={`${percentColor} px-2 py-1 rounded`}
                        style={percentbgColor ? { backgroundColor: percentbgColor } : {}}
                    >
                        {percent}
                    </span>
                    <span className="text-gray-500 font-normal whitespace-nowrap">
                        Compared to last month
                    </span>
                </p>
            )}

        </div>
    );
}